"""Bundle src/*.yaml into openapi.yaml, inlining example references used inside example values."""

import copy
import glob
import re

import yaml

text = "".join(open(p, encoding="utf-8").read() for p in sorted(glob.glob("src/*.yaml")))
spec = yaml.safe_load(text)
examples = spec["components"]["examples"]
PREFIX = "#/components/examples/"


def resolve(node, in_example=False):
    if isinstance(node, dict):
        ref = node.get("$ref")
        if in_example and isinstance(ref, str) and ref.startswith(PREFIX) and len(node) == 1:
            name = ref[len(PREFIX) :].split("/")[0]
            return resolve(copy.deepcopy(examples[name]["value"]), True)
        out = {}
        for k, v in node.items():
            child_in_example = in_example or k in ("example", "value")
            out[k] = resolve(v, child_in_example)
        return out
    if isinstance(node, list):
        return [resolve(v, in_example) for v in node]
    return node


# examples at components level stay as-is (values may reference each other)
bundled = resolve(spec)
# Operations without `security` are public: make that explicit.
for path, item in bundled["paths"].items():
    for method, op in item.items():
        if method in ("get", "post", "put", "patch", "delete") and "security" not in op:
            op["security"] = []
        if method in ("get", "post", "put", "patch", "delete") and "summary" not in op:
            oid = op.get("operationId", method + " " + path)
            words = re.sub(r"([A-Z])", r" \1", oid).strip().lower()
            op["summary"] = words[:1].upper() + words[1:]
        if method in ("get", "post", "put", "patch", "delete"):
            params = op.setdefault("parameters", [])
            refs = {p.get("$ref") for p in params if isinstance(p, dict)}
            for extra in ("TenantId", "RequestId"):
                ref = "#/components/parameters/" + extra
                if ref not in refs:
                    params.append({"$ref": ref})
            schemes = {k for req in op.get("security", []) for k in req}
            optional = any(req == {} for req in op.get("security", []))
            if (
                schemes & {"terminalAuth", "cashierAuth"}
                and not optional
                and not path.endswith("/receipt.pdf")
            ):
                for extra in ("DeviceId", "DeviceTimestamp", "DeviceSignature"):
                    ref = "#/components/parameters/" + extra
                    if ref not in refs:
                        params.append({"$ref": ref})
            codes = [str(c) for c in op.get("responses", {})]
            if not any(c.startswith("4") for c in codes):
                if op.get("security"):
                    op["responses"]["401"] = {"$ref": "#/components/responses/Unauthorized"}
                else:
                    op["responses"]["422"] = {"$ref": "#/components/responses/Unprocessable"}

bundled["components"].pop("examples", None)  # inlined above


class Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


with open("openapi.yaml", "w", encoding="utf-8") as f:
    f.write("# GENERATED by build.py from src/*.yaml — edit the sources, then run: python3 build.py\n")
    yaml.dump(bundled, f, Dumper=Dumper, sort_keys=False, allow_unicode=True, width=120)
print("paths:", len(bundled["paths"]), "schemas:", len(bundled["components"]["schemas"]))
